package com.scorpio.distancecalculator

const val APPLICATION_CREATED = "APPLICATION_CREATED"
const val APPLICATION_PAUSED = "APPLICATION_PAUSED"
const val RUNNING_SERVICE_STARTED = "RUNNING_SERVICE_STARTED"
const val RUNNING_SERVICE_PAUSED = "RUNNING_SERVICE_PAUSED"

const val WORKER_STARTED = "WORKER_STARTED"
const val WORKER_ENDED = "WORKER_ENDED"
